# Generated by Django 5.2.11 on 2026-02-15 03:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Vaccine name (e.g., 'Rabies', 'DHPP')", max_length=200, unique=True)),
                ('manufacturer', models.CharField(blank=True, help_text='Pharmaceutical company', max_length=200)),
                ('description', models.TextField(blank=True, help_text='What the vaccine protects against')),
                ('species_target', models.CharField(blank=True, help_text="Target species (e.g., 'dog', 'cat', 'all')", max_length=50)),
                ('duration_months', models.PositiveIntegerField(help_text='Validity period in months (for next dose calculation)', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_mandatory', models.BooleanField(default=False, help_text='Whether this vaccine is legally required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vaccine',
                'verbose_name_plural': 'Vaccines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(help_text='Contact email', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Associated user account', on_delete=django.db.models.deletion.CASCADE, related_name='pessoa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('species', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('rabbit', 'Rabbit'), ('hamster', 'Hamster'), ('reptile', 'Reptile'), ('other', 'Other')], help_text='Type of animal', max_length=20)),
                ('breed', models.CharField(blank=True, help_text='Breed (if applicable)', max_length=100)),
                ('birth_date', models.DateField(help_text='Date of birth')),
                ('color', models.CharField(blank=True, max_length=50)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the pet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pessoa', models.ForeignKey(help_text='Pet pessoa', on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='core.pessoa')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administered_date', models.DateField(help_text='Date the vaccine was given')),
                ('veterinarian_name', models.CharField(help_text='Name of the veterinarian who administered the vaccine', max_length=200)),
                ('clinic_name', models.CharField(blank=True, help_text='Veterinary clinic name', max_length=200)),
                ('batch_number', models.CharField(blank=True, help_text='Vaccine batch/lot number', max_length=100)),
                ('next_dose_date', models.DateField(blank=True, help_text='Calculated date for next dose', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional observations or reactions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(help_text='Pet that received the vaccine', on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='core.pet')),
                ('vaccine', models.ForeignKey(help_text='Vaccine administered', on_delete=django.db.models.deletion.PROTECT, related_name='vaccination_records', to='core.vaccine')),
            ],
            options={
                'verbose_name': 'Vaccination Record',
                'verbose_name_plural': 'Vaccination Records',
                'ordering': ['-administered_date'],
            },
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['pessoa', '-created_at'], name='core_pet_pessoa__e874b5_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['species'], name='core_pet_species_62d417_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccinationrecord',
            index=models.Index(fields=['pet', '-administered_date'], name='core_vaccin_pet_id_6e8240_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccinationrecord',
            index=models.Index(fields=['vaccine'], name='core_vaccin_vaccine_791159_idx'),
        ),
        migrations.AddIndex(
            model_name='vaccinationrecord',
            index=models.Index(fields=['next_dose_date'], name='core_vaccin_next_do_3cb025_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vaccinationrecord',
            unique_together={('pet', 'vaccine', 'administered_date')},
        ),
    ]
